### ISSUE TITLE
Dashes in the database name is not supported

### ISSUE THREAD

**Issue by odalabasmaz** [grafana/timestream-datasource#10]
When created a database with the name "net-example" that has a dash in it, we can't use it in Grafana dashboards.
I observed the request/response during query;

**Request:**
endpoint: {host}/api/ds/query
rawQuery: "SHOW TABLES FROM net-example"

**Response:**
400 Bad Request
error: "ValidationException: The query syntax is invalid at line 1:21"

**Comment by ryantxu** [comment]
For user queries, you should always quote the table and database, and column names.  We will update the templates to make this more clear

**Comment by rk-yen** [comment]
Having underscores in table name didn't show the table name even during the "adding datasource" step.
