### ISSUE TITLE
$__interval - Feature Request

### ISSUE THREAD

**Issue by InteliClic** [grafana/timestream-datasource#100]
We having been using timestream with grafana and it's working pretty well.

The $__interval however doesn't render and this would be extremely useful for bin queries to specify how far apart the points should be.

**Comment by InteliClic** [comment]
![image](https://user-images.githubusercontent.com/1582354/164369882-3f60bc84-ac0a-44b1-a133-735f4df7ff57.png)

This is what I get when I type the $ into the grafana query editor. If I use $__interval I don't get any results.

**Comment by yaelleC** [comment]
Hi @InteliClic , could you confirm that you are using the latest timestream version? (1.5.0 or over)?
Trying to repro what you describe: I don't see `$__interval` in suggestions either but I can use it nonetheless.

**Comment by InteliClic** [comment]
I found it in Grafana! The plugin I was using was 1.1.12. I updated to 1.5.1 and $__interval is infact working. A quick note in the readme to update to the most recent version of the plugin inside grafana would be helpful! Thanks for all your hard work!
