### ISSUE TITLE
Arm64 support

### ISSUE THREAD

**Issue by mouse256** [grafana/timestream-datasource#102]
I wanted to run my Grafana instance on an Arm64-linux machine, which works fine. But then I discovered that the timestream plugin does not support Arm64.
Would it be possible to make a build for Arm64-linux too?

**Comment by Ramos-Guilherme** [comment]
> I wanted to run my Grafana instance on an Arm64-linux machine, which works fine. But then I discovered that the timestream plugin does not support Arm64. Would it be possible to make a build for Arm64-linux too?

same here. Any news?

**Comment by andresmgot** [comment]
the last release include binaries for ARM: https://github.com/grafana/timestream-datasource/releases/tag/v1.4.0 can you try them? 

https://github.com/grafana/timestream-datasource/releases/download/v1.4.0/grafana-timestream-datasource-1.4.0.linux_arm64.zip

**Comment by mouse256** [comment]
Installation fails for me on raspberry-pi ARM64 (the log is unclear, shows some html)
Just a guess, but https://grafana.com/grafana/plugins/grafana-timestream-datasource/?tab=installation only lists the `arm` version, not `arm64` ?

**Comment by andresmgot** [comment]
how did you install it and what error do you get?



> Just a guess, but https://grafana.com/grafana/plugins/grafana-timestream-datasource/?tab=installation only lists the `arm` version, not `arm64` ?

That seems a documentation issue. The release page on GitHub contains a version for arm64

**Comment by mouse256** [comment]
I'm using the `grafana/grafana:8.3.3` docker image on a RaspberryPi4 (arm64). If failed both using the GUI as when using the `grafana-cli`. (other plugins install fine that way)
I got it working by downloading the zip manually from github and extracting to the plugins folder of grafana.

Error during installation attached. [error.txt](https://github.com/grafana/timestream-datasource/files/7880849/error.txt)

Maybe because https://grafana.com/api/plugins/grafana-timestream-datasource/versions/1.4.0/download?os=linux&arch=arm exists, but https://grafana.com/api/plugins/grafana-timestream-datasource/versions/1.4.0/download?os=linux&arch=arm64 does not.
Possibly the plugin api tries to download it like that?

**Comment by andresmgot** [comment]
Thanks for the details @mouse256, the missing API is interesting, it could be related to the issue. I have seen this issue in other plugins too: https://github.com/grafana/athena-datasource/issues/94

**Comment by taleena** [comment]
This is failing on command line, workaround is to use the URL, we are still investigating.

**Comment by andresmgot** [comment]
@mouse256 there was a bug in the release process that caused the binaries for arm64 to be missing. That is now fixed and the binaries are now properly uploaded. Let us know (and reopen) if you still find this issue!

**Comment by mouse256** [comment]
Works fine now, thanks!
