### ISSUE TITLE
Make it possible to sync time field with time range

### ISSUE THREAD

**Issue by sunker** [grafana/timestream-datasource#103]
Currently there's no way to sync the time field that is used in the raw query with the time range in the dashboard. We should add macros that makes this possible. 

Suggested macros to be added: 
`$__timeFrom()` Will be replaced by the start of the currently active time selection.
`$__timeTo()` Will be replaced by the end of the currently active time selection.

For reference, see the [postgres](https://grafana.com/docs/grafana/latest/datasources/postgres/) docs.

**Comment by zoltanbedi** [comment]
Fixed in #98
