### ISSUE TITLE
Bytes metered in query stats in Timestream data source

### ISSUE THREAD

**Issue by gadiraa** [grafana/timestream-datasource#106]
We were wondering if it is possible to easily add the bytes metered by a query to the query stats of a Grafana panel? Timestream’s query response has that information which is updated with every paginated call during query in progress and reaches a final value once the query execution finishes.
 
"QueryStatus": { 
      "CumulativeBytesMetered": number,
      "CumulativeBytesScanned": number,
      "ProgressPercentage": number
   },

**Comment by sudiptodas** [comment]
Yes, please, in the Stats view. That way its easier to discover for customers, and the value is more human readable.

**Comment by farzadpanahi** [comment]
It would be great if we could have both `BytesMetered` and `BytesScanned`. A quick way to see the bytes scanned for small queries and also to see how much AWS is overcharging us with their ridiculous [10MB round-up pricing policy](https://aws.amazon.com/timestream/pricing/#:~:text=rounded%20up%20to%20the%20nearest%20megabyte%2C%20with%20a%2010MB%20minimum%20per%20query)!
