### ISSUE TITLE
AWS Auth Provider should be able to refresh token itself

### ISSUE THREAD

**Issue by odalabasmaz** [grafana/timestream-datasource#11]
When using AWS Auth Provider with providing a Role ARN to assume, it expires after a while, and the dashboard starts failing to gather data.
It'd be great if it can refresh the token itself, otherwise, we have to browse the data source settings and click to `save & test` button again.
<img width="492" alt="image" src="https://user-images.githubusercontent.com/9153701/95687032-d902a400-0c09-11eb-8022-2fc2fc87309a.png">

**Comment by tuxtek** [comment]
We have also run into this issue recently while investigating Timestream as an alternative to our current time series db.

**Comment by alex-berger** [comment]
Same here

**Comment by mark-kaghazgarian** [comment]
+1

**Comment by ryantxu** [comment]
I am working on a possible fix -- that starts with unifying configuration with various services.  If anyone can try a dev build from:
https://app.circleci.com/pipelines/github/grafana/timestream-datasource/105/workflows/bf72c017-8cf7-4b45-94c7-d5c0312c9974/jobs/281/artifacts

and let me know how that goes, it would be appreciated

**Comment by johan-smits** [comment]
It works when you go to the connector and you press save and test. But it is only for a while when the token times out again.
