### ISSUE TITLE
chore: migrate to Drone

### ISSUE THREAD

**Issue by vickyyyyyyy** [grafana/timestream-datasource#115]
We are no longer using CircleCI for most of our builds, including Grafana: https://drone.grafana.net/grafana/grafana

Migrate from CircleCi to Drone: https://drone.grafana.net/grafana/timestream-datasource/settings

**Comment by andresmgot** [comment]
so drone is already working in the repo as you pointed (https://drone.grafana.net/grafana/timestream-datasource). We just need to disable CircleCI. I tried but I am not a repo admin so I cannot disable it. @ryantxu can you make @grafana/cloud-datasources admin of the repository?
