### ISSUE TITLE
Can't authenticate against Timestream instance in localstack

### ISSUE THREAD

**Issue by the-gilbs** [grafana/timestream-datasource#119]
**What happened**:
I have an instance of timestream running in [localstack](https://github.com/localstack/localstack/blob/master/README.md). I can write data to it and query it fine.   I can't get the plugin to connect.  It seems to require a role ARN, even though the tooltip says it's optional:
 
![Screen Shot 2021-12-03 at 11 35 05 AM](https://user-images.githubusercontent.com/80845575/144644352-38e0b323-81de-422c-98ef-46f75a91e778.png)

Giving it a dummy arn, I can't figure out what's wrong, given either localstack or grafana logs:

![Screen Shot 2021-12-03 at 12 10 38 PM](https://user-images.githubusercontent.com/80845575/144644453-a03abc74-b984-43fa-9079-e5b88a67baec.png)

**What you expected to happen**:

Some easy way to connect to a localstack Timestream. 

**How to reproduce it (as minimally and precisely as possible)**:
Run timestream in localstack, using docker-compose yaml:

version: "3.8"

services:
  localstack:
    container_name: "${LOCALSTACK_DOCKER_NAME-localstack_main}"
    image: localstack/localstack
    network_mode: bridge
    ports:
      - "0.0.0.0:53:53"                # only required for Pro
      - "0.0.0.0:53:53/udp"            # only required for Pro
      - "0.0.0.0:443:443"              # only required for Pro
      - "0.0.0.0:4510-4530:4510-4530"  # only required for Pro
      - "0.0.0.0:4566:4566"
      - "0.0.0.0:4571:4571"
    environment:
      - SERVICES=${SERVICES- }
      - DEBUG=${DEBUG- }
      - DATA_DIR=${DATA_DIR- }
      - LAMBDA_EXECUTOR=${LAMBDA_EXECUTOR- }
      - LOCALSTACK_API_KEY=${LOCALSTACK_API_KEY- }  # only required for Pro
      - HOST_TMP_FOLDER=${TMPDIR:-/tmp/}localstack
      - DOCKER_HOST=unix:///var/run/docker.sock
      - DEBUG=1
    volumes:
      - "${TMPDIR:-/tmp}/localstack:/tmp/localstack"
      - "/var/run/docker.sock:/var/run/docker.sock"

Set services to timestream,iam,sts

Try connecting the plugin, set endpoint to: http://host.docker.internal:4566

**Screenshots**

**Anything else we need to know?**:

**Environment**:
- Grafana version: 7.1.0
- Plugin version:
- OS Grafana is installed on:
- User OS & Browser:
- Others:

**Comment by sunker** [comment]
Thanks for creating this issue @the-gilbs. 

My guess is that the IAM user doesn't have the policies that allows access to the Timestream API. Can you attach this minimal policy to you user? 
```json
{
  "Version": "2012-10-17",
  "Statement": [
    {
      "Effect": "Allow",
      "Action": ["timestream:*"],
      "Resource": "*"
    }
  ]
}
```

Let me know if it solved the problem. 

This should be in the Timestream data source documentation. Just made a [PR](https://github.com/grafana/timestream-datasource/pull/120) for adding this to the docs.

**Comment by the-gilbs** [comment]
Thanks for the response. This ended up being a localstack issue, they didn't handle a blank assume-role correctly. It was just difficult to tell from the error messages if it was front or back-end (e.g. a 200 response code, but still an error)

**Comment by sunker** [comment]
Okay, thanks for quick reply. I'll close the issue then.
