### ISSUE TITLE
Migrate plugin to use sqlds (requires a golang SQL driver) and the aws-sdk SQL packages.

### ISSUE THREAD

**Issue by andresmgot** [grafana/timestream-datasource#130]

**Comment by andresmgot** [comment]
After some investigation, we have decided to not move forward with the integration of sqlds and the SQL package of the aws-sdk because the plugin currently support:

 - Non SQL fields like time series, arrays and rows.
 - Several time series per query
 - Custom labeling
 - Paginated responses

The libraries are not adapted to handle that (and they probably shouldn't, for some of the items, to be generic). More information about this [in this document](https://docs.google.com/document/d/1tnAPiPTkVSRBSbq8_A9TCp2jCSRiPuwWOR3VnQmOZTs/).

**Comment by taleena** [comment]
Effort for this was captured in https://github.com/grafana/timestream-datasource/issues/131 (and was originally an estimate prior to doing the work).
