### ISSUE TITLE
General Guidance: increasing limits in AWS Teamstream quotas

### ISSUE THREAD

**Issue by Jihad7** [grafana/timestream-datasource#15]
cx asking whether possible it’s to increase the default quotas https://docs.aws.amazon.com/timestream/latest/developerguide/ts-limits.html#limits.default ?
customer would like to know if it’s possible to get a list of all Timestream service limitations that can be increased with clearly stated hard limits for specific region aws eu-west-1?

**Comment by tiratatp** [comment]
Please contact AWS Support for help with your limits.
