### ISSUE TITLE
Getting duplicate legends in Grafana when using selecting for a particular measure_name

### ISSUE THREAD

**Issue by flycast** [grafana/timestream-datasource#161]
**What happened**:
I have data with multiple measurements in AWS Timestream.  When I use the following query I get multiple data legends:
SELECT * FROM "sampleDB"."LgFlaminator" where measure_name = 'PolyPressure'

![image](https://user-images.githubusercontent.com/32281377/163813006-4ee6d798-2c1b-4b1c-92db-b56bd21fa8c7.png)

**What you expected to happen**:
I expected that I would get a single data series with a single legend.
I find that I have to call the query like this to get the result I wanted:
SELECT time, measure_value::double FROM "sampleDB"."LgFlaminator" where measure_name = 'PolyPressure'

![image](https://user-images.githubusercontent.com/32281377/163813290-61c2d117-8bea-4fbb-ab37-b17d5a609ece.png)

**How to reproduce it (as minimally and precisely as possible)**:

Example:

1. Add multiple data points for two different measurement names to Timestream.
2. Create query

**Anything else we need to know?**:

**Environment**:
- Grafana version: Cloud [v8.4.6 (c53173ff6)]()
- Plugin version: AWS Timestream plugin 1.5.1
- OS Grafana is installed on: Cloud version
- User OS & Browser: Windows 10, Chrome

**Comment by sarahzinger** [comment]
@flycast I see 2 markers like that when the table I'm trying to query has 2 numeric columns, perhaps if you switch to a table view, you'll see something similar that could explain what is going on:

![Screen Shot 2022-04-18 at 1 58 56 PM](https://user-images.githubusercontent.com/6620164/163855998-31e2f036-9264-4a2c-8f07-ce49b117c1fa.png)

In the case above, AWS is returning back to us 2 columns that I believe can be the same value in different formats for the same measurement (although interestingly in this sample dataset, one of the columns is always empty)

The visualization does not know which column you would like to render and so it renders both. As you point out you can use sql syntax to narrow down to render just the fields you are interested in.

I believe this is as designed so I'll close the issue, but if I'm misunderstanding something let me know and I'm happy to reopen it!
