### ISSUE TITLE
Cannot regenerate golden files for executor_test.go from scratch

### ISSUE THREAD

**Issue by nekketsuuu** [grafana/timestream-datasource#183]
This is a bug-like issue on development of this plugin.

**What happened**:

I want to regenerate `*.golden.txt` files under `pkg/timestream/testdata` in order to send a pull request. So I prepared `grafanaDB.DevOps` table on my own AWS account using "sample database" feature (described below), and commented out the following line, and run [`TestGenerateTestData`](https://github.com/grafana/timestream-datasource/blob/0832f2597e8717654fa501fb0e9dbe1269b3f2be/pkg/timestream/executor_test.go#L62).

https://github.com/grafana/timestream-datasource/blob/0832f2597e8717654fa501fb0e9dbe1269b3f2be/pkg/timestream/executor_test.go#L63-L64

But the run is failed with messages, for example, ``execute failed ValidationException: line 5:8: Column 'availability_zone' does not exist``. This is because some queries want certain column names which my records in `grafanaDB.DevOps` don't have.

https://github.com/grafana/timestream-datasource/blob/0832f2597e8717654fa501fb0e9dbe1269b3f2be/pkg/timestream/executor_test.go#L110

So... it seems these test cases for `pkg/timestream/executor_test.go` assume some private records in `grafanaDB.DevOps` table. I may guess what columns are needed and add them to my table, but it's a bit tired to me.

Therefore, could someone add a timestream-write script to set up a table for `executor_test.go` to this repository and write a how-to-test document? Or, would someone simplify test cases to use names only in the sample database?

**What you expected to happen**:

I can regenerate test data easily.

**How to reproduce it (as minimally and precisely as possible)**:

1. Create a sample database of Amazon Timestream with following configs:
    - region: us-west-2
    - database name: grafanaDB
    - sample table: DevOps with single-measure records
2. Comment out `t.Skip("Integration Test")` in `executor_test.go`.
3. Run test case `TestGenerateTestData`.

Screenshot of Management Console to create the database:

<img width="662" alt="A screenshot of a web page which displays configs described above" src="https://user-images.githubusercontent.com/4374702/181837370-af3a63b6-b788-4ef0-b29c-467bb19b5570.png">

**Environment**:

- Plugin version: v2.1.0 (0832f2597e8717654fa501fb0e9dbe1269b3f2be)
- User OS: macOS
- Go: go1.18.4 darwin/amd64

**Comment by sarahzinger** [comment]
Hello! Thanks for reporting this issue! I took a look at this as part of triaging new tickets, and also ran into issues trying to run this "TestGenerateTestData" function. I haven't looked deeply enough to identify what's going on, but I think at the very least the suggestion here for a help doc seems warranted. Going to move this to our backlog as it seems worth investigating although I'm not sure on a specific timeline for a fix yet. Will bring it up with the team.
