### ISSUE TITLE
Use getDefaultQuery method to set default query

### ISSUE THREAD

**Issue by sunker** [grafana/timestream-datasource#203]
Instead of calling onChange to set default query for new queries, we should use the new [getDefaultQuery](https://github.com/grafana/grafana/blob/main/packages/grafana-data/src/types/datasource.ts#L360) method defined in the data source api. We can use the same default query as today. https://github.com/grafana/timestream-datasource/blob/05ff4000954b4dd467a3995624c2954eb8af3e9e/src/components/QueryEditor.tsx#L24-L28

Part of https://github.com/grafana/cloud-data-sources/issues/79

**Comment by idastambuk** [comment]
Closing as "won't do"
See https://github.com/grafana/oss-plugin-partnerships/issues/79#issuecomment-1549740717 for info
