### ISSUE TITLE
Document how to use with IAM Roles with EKS Service accounts

### ISSUE THREAD

**Issue by palsivertsen** [grafana/timestream-datasource#21]
When running Grafana in AWS EKS with [IAM roles for service accounts](https://docs.aws.amazon.com/eks/latest/userguide/iam-roles-for-service-accounts.html) it's not obvious why it's not picking up the correct credentials and how to get things working.

I got this working by specifying "Credentials File" as auth provider and specifying a security context for the pod running Grafana as described in the [CloudWatch datasource documentation](https://grafana.com/docs/grafana/latest/datasources/cloudwatch/#eks-iam-roles-for-service-accounts).

Hope this saves someone some hours ;)

**Comment by ryantxu** [comment]
Can you check the latest 1.1.0 release -- the authentication now matches cloudwatch.  See https://grafana.com/docs/grafana/latest/datasources/cloudwatch/#authentication

if you still have questions, let us know
