### ISSUE TITLE
[v 1.1.1] Unable to create Query variable with 't is undefined' error

### ISSUE THREAD

**Issue by zolotukhin** [grafana/timestream-datasource#38]
We are trying to use 1.1.1 plugin with Grafana v7.3.4 (14c494085e).
With this version we are unable to instantiate Query variables with the following error:

`t is undefined`
`Templating [<SOMETHING>]
Error updating options: t is undefined`

Sample query:

`SELECT DISTINCT <SOMETHING> FROM "<DATABASE>"."<TABLE>" WHERE <SOMETHING> IS NOT NULL`

Multi-value
Include All option
Custom all value: All

**Comment by mark-lvl** [comment]
Variable in queries needs to be in this format: ${SOEMTHING}
e.g. "SELECT ${SOMETHING} FROM DB.TABLE"

**Comment by zolotukhin** [comment]
How is it different to the one I posted? We just need distinct non-null values. Thanks

**Comment by zolotukhin** [comment]
That got fixed in 1.1.2. Thanks.
But now it fails in different way https://github.com/grafana/timestream-datasource/issues/41
