### ISSUE TITLE
[v 1.1.2] Firefox: Unable to create Query variable with 'e.data[0] is undefined' error

### ISSUE THREAD

**Issue by zolotukhin** [grafana/timestream-datasource#41]
We are trying to use 1.1.2 plugin with Grafana v7.3.4 (14c494085e).
With this version we are unable to instantiate Query variables with the following error:
`
Validation
e.data[0] is undefined
`
`
Templating [<SOMETHING>]
Error updating options: e.data[0] is undefined
`
Sample query:
`
SELECT DISTINCT <SOMETHING> FROM "<DATABASE>"."<TABLE>" WHERE <SOMETHING> IS NOT NULL
`
Multi-value
Include All option
Custom all value: All

Fails exactly here:
```
TypeError: e.data[0] is undefined
    t DataSource.ts:227
    RxJS 6
```

**Comment by zolotukhin** [comment]
```
TypeError: e.data[0] is undefined
    t DataSource.ts:227
    RxJS 6
```

**Comment by zolotukhin** [comment]
Tested, it works in Chromium based browsers.
The issue appears in Firefox

**Comment by aaneja** [comment]
I could reproduce this issue on Chrome too. Here's a flow that reproduces it for me:
1. Set the Query variable to refresh `On Dashboard Load`
2. On dashboard load I see a `/query` call made for the variable (ie `SELECT DISTINCT <SOMETHING> FROM "<DATABASE>"."<TABLE>" WHERE <SOMETHING> IS NOT NULL`). If this call takes > 5s , subsequent call is made to Timestream
3. This subsequent call contains a `nextToken` and it appears that while parsing results it fails with
```
actions.ts:631 TypeError: Cannot read property 'fields' of undefined
    at t [as project] (DataSource.ts:227)
    at t._next (map.js:35)
    at t.next (Subscriber.js:53)
    at t.__tryOrUnsub (Subscriber.js:192)
    at t.next (Subscriber.js:130)
    at t._next (Subscriber.js:76)
    at t.next (Subscriber.js:53)
    at Object.next (requestLooper.ts:59)
    at t.__tryOrUnsub (Subscriber.js:192)
    at t.next (Subscriber.js:130)
```
