### ISSUE TITLE
Incorrect regions added in v1.1.2

### ISSUE THREAD

**Issue by lewalt000** [grafana/timestream-datasource#42]
In v1.1.2, the regions supported by the plugin were updated to reflect where Timestream is available.

However, the available West Coast region is us-west-2, and not us-west-1: https://github.com/grafana/timestream-datasource/blob/master/src/common/regions.ts

This is confirmed in the pricing page which shows available regions: https://aws.amazon.com/timestream/pricing/. Note: "US West (Oregon)" is us-west-2

This causes the Grafana UI to not allow us-west-2 to be configured as a Timestream data source. It allows us-west-1, where Timestream is not currently supported.

**Comment by squalou** [comment]
HI,
I faced the same issue : which is a GUI deign error more than an issue : **you can** fill in whatever value you need, even if not listed !

It is not natural for a dropdown menu, nothing tells you you can, it requires a "usability fix".

Remove entirely the dropdown would be better than this.

see #19 
(that's where I found the idea to 'type in', no-one can guess that)

**Comment by agranig** [comment]
Same with the pre-defined eu-west-2 region, which is actually supposed to be eu-west-1.

**Comment by ryantxu** [comment]
resolved in v1.2.0
