### ISSUE TITLE
Query errors when authenticated using "AWS SDK Default" connection method

### ISSUE THREAD

**Issue by squalou** [grafana/timestream-datasource#44]
Hi,

I've set my Grafana to use a role that contains all required IAM resources to access Timestream.
As a result : in the config panel, simply setting "AWS SDK Default" and region => connection works, databases and tables are discovered, that's great.

BUT whenever I try a query, I get 

```
ValidationException: Invalid pagination token.
```

Setting up a user with the exact same policies (same role attached), defining Access Key / Secret key method in the plugin connection : it works fine.

**Comment by tiratatp** [comment]
You should contact AWS Support and tell them your request id and pagination token using Query Inspector: https://community.grafana.com/t/using-grafanas-query-inspector-to-troubleshoot-issues/2630

**Comment by squalou** [comment]
Unable to reproduce today.
I don't get it ... anyway  closing, and if it ever happens again I'll do as you suggest.

Thanks for the advice !
