### ISSUE TITLE
$__timefilter variable issue on armhf (e.g. raspberry) 

### ISSUE THREAD

**Issue by mg-arne** [grafana/timestream-datasource#52]
I complied the plugin from source for armhf, which is used by the raspberries. The plugin is working in general, but the variable $__timefilter seems to have an issue. The timestamps are incorrect and sometimes negative. It looks like a 32bit overrun issue?! 

My filter in grafana is set to from 2013-10-03 00:00:00 to 2013-10-04 23:59:59 and that results in 
"time BETWEEN from_milliseconds(2066697984) AND from_milliseconds(-2055470312)". As you can see the second timestamp is negative, which I believe should not be the case.

**Comment by mg-arne** [comment]
I think I found the root cause and created a pull request to fix the issue: https://github.com/grafana/timestream-datasource/pull/53. I tested it on my raspberry and the plugin is running as expected now.

Issue is described here: https://github.com/golang/go/issues/23086

**Comment by ryantxu** [comment]
Closed by #53
