### ISSUE TITLE
$__measure macro value wrapped in quotes

### ISSUE THREAD

**Issue by JeffAshton** [grafana/timestream-datasource#56]
It appears that the `$__measure` values are getting wrapped in double quotes (`"`) when formatting the query.

Grafana:  v7.3.7
Amazon Timestream:  v1.1.2

Query Template:

```
WITH published_messages AS (
    SELECT
        BIN(time, $__interval_ms) as binned_time,
        dc,
        SUM( measure_value::double ) AS measure_value
    FROM $__database.$__table
    WHERE (
        $__timeFilter
        AND measure_name = '$__measure'
    )
    GROUP BY BIN(time, $__interval_ms), dc
)
SELECT
    dc,
    CREATE_TIME_SERIES( binned_time, measure_value ) AS "count"
FROM published_messages
GROUP BY dc
```

Actual query via inspector:

```
WITH published_messages AS (
    SELECT
        BIN(time, 2000ms) as binned_time,
        dc,
        SUM( measure_value::double ) AS measure_value
    FROM "metrics"."iot_messages"
    WHERE (
        time BETWEEN from_milliseconds(1611782023493) AND from_milliseconds(1611783823493)
        AND measure_name = '"published_messages"'
    )
    GROUP BY BIN(time, 2000ms), dc
)
SELECT
    dc,
    CREATE_TIME_SERIES( binned_time, measure_value ) AS "count"
FROM published_messages
GROUP BY dc
```

You'll notice that the measurement name contains an extra set of double quotes `"` inside the single quotes from the query template.  This also appears to be happening with the database and table macro values, but double quotes are acceptable 
in this case, where as double quotes are not acceptable for measurement names.

I have verified that the `measure_name` values do not contain quotes in the Timestream UI.

**Comment by ryantxu** [comment]
If you are able to try with a development build -- can you check what happens with:
https://app.circleci.com/pipelines/github/grafana/timestream-datasource/161/workflows/a9b6f1aa-de43-4ab0-a498-c772eb98a9a4/jobs/630/artifacts

This includes:
https://github.com/grafana/timestream-datasource/commit/7da9b30f179b91d205fdc24460145ce2df2ccf18

**Comment by JeffAshton** [comment]
Thanks @ryantxu, that definitely sounds like the fix for this issue.  Switching to the development build is probably more hassle then what it's worth for me at the moment.  What's the release schedule for this plugin?

**Comment by JeffAshton** [comment]
Fixed by https://github.com/grafana/timestream-datasource/pull/47
