### ISSUE TITLE
Error in grafana Windows: Modified signature

### ISSUE THREAD

**Issue by rreimi** [grafana/timestream-datasource#59]
I'm getting the following error in Grafana for Windows after installing the timestream plugin

![image](https://user-images.githubusercontent.com/3412034/107077735-350abd00-67e5-11eb-9c9c-beb0f9621d10.png)

**Comment by joshualan** [comment]
Bump, I'm encountering the exact same issue.

**Comment by ryantxu** [comment]
Can you try in the latest grafana release?  This was an issue with grafana core (not the plugin)
