### ISSUE TITLE
Parsing plugin's response

### ISSUE THREAD

**Issue by jugurthab** [grafana/timestream-datasource#60]
Hi,

I'm new to grafana and react,

I would like to create a custom panel (html+js) for out client needs. So I need to parse the response from the plugin :

Suppose I have a response with the following form :

dataframes | [ "QVJST1cxAAD/////eAQAABAAAAAAAAoADgAMAAsABAAKAAAAFAAAAAAAAAEDAAoADAAAAAgABAAKAAAACAAAAIwBAAADAAAATAAAACgAAAAEAAAAFPz//wgAAAAMAAAAAQAAAEEAAAAFAAAAcmVmSWQAAAA0/P//CAAAAAwAAAAAAAAAAAAAAAQAAABuYW1lAAAAAFT8//8IAAAAJAEAABoBAAB7ImN1c3RvbSI6eyJleGVjdXRpb25TdGFydFRpbWUiOjE2MTI5Njg0ODE2NDQsImV4ZWN1dGlvbkZpbmlzaFRpbWUXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX//xYAAABtZWFzdXJlX3ZhbHVlOjp2YXJjaGFyAAAq////FAAAAEwAAABUAAAAAAADAVQAAAABAAAABAAAABj///8IAAAAIAAAABUAAABtZWFzdXJlX3ZhbHVlOjpkb3VibGUAAAAEAAAAbmFtZQAAAAAAAAAAAAAGAAgABgAGAAAAAAACABUAAABtZWFzdXJlX3ZhbHVlOjpkb3VibGUAAACu////FAAAADgAAAA4AAAAAAAFATQAAAABAAAABAAAAJz///8IAAAADAAAAAMAAAB2aW4ABAAAAG5hbWUAAAAAAAAAAJD///8DAAAAdXXXXXXXXXXXXXXXXXXXXXX=" ]
-- | -

It looks like base64, but when I decode it, only a portion is displayed correctly.

How can I parse the above response?

Thank's.

**Comment by jugurthab** [comment]
Hi,

Does anyone knows the answer?

thanks.

**Comment by ryantxu** [comment]
Try https://github.com/grafana/grafana/blob/4f61edd28df8c5cfbbb2da4335b189d25a59e7d0/packages/grafana-runtime/src/utils/queryResponse.ts#L33

It is base64 encoded apache arrow files -- use the function above (note that queries is optional) and you won't need to deal with the details.

Or just use a panel plugin and you will get the parsed data directly

**Comment by ryantxu** [comment]
I'll close here and you can ask again in the grafana channel if not sufficient
