### ISSUE TITLE
eu-west-1 region missing

### ISSUE THREAD

**Issue by paulhopkins11** [grafana/timestream-datasource#61]
Timestream is not supported in London region but eu-west-2 is shown in the list. Ireland regions is supported but eu-west-1 is not in the list. I can only choose from the list and not enter this manually.
![image](https://user-images.githubusercontent.com/9349198/107574948-29edcd80-6be7-11eb-8d5d-e5b7ed540b1d.png)

This is the list of supported regions
![image](https://user-images.githubusercontent.com/9349198/107575136-6d483c00-6be7-11eb-97b4-4b1f3c2b80b6.png)

**Comment by jugurthab** [comment]
Hi,

I had the same issue, but seems like that made a fix recently : https://github.com/grafana/timestream-datasource/commit/6bc5b2628c59ef19cfe2ffe9efe31d23b06195e5. I guess it will be available in the next release.

**Comment by tiratatp** [comment]
I saw in other thread that you can manually type this.

**Comment by tiratatp** [comment]
This will be fixed after the next release since https://github.com/grafana/timestream-datasource/commit/6bc5b2628c59ef19cfe2ffe9efe31d23b06195e5 was merged

**Comment by mstfldmr** [comment]
I see that "eu-west-2" in module.js and module.js.map files. However, if I change them manually, Grafana disables the plugin because of mismatching signature.

Can I sign the plugin myself or disable signature checking in my development environment until the next release is published?

**Comment by tiratatp** [comment]
This should be fixed by https://github.com/grafana/timestream-datasource/releases/tag/v1.2.0

**Comment by ryantxu** [comment]
released in 1.2.0
