### ISSUE TITLE
Can't install the latest version of plugin

### ISSUE THREAD

**Issue by tsunejui** [grafana/timestream-datasource#79]
I got error message while installing the latest plugin:

![image](https://user-images.githubusercontent.com/6142903/112926727-7153fd00-9146-11eb-8489-6b04a26cc000.png)

But it works fine on 1.2.0:

![image](https://user-images.githubusercontent.com/6142903/112926773-86c92700-9146-11eb-828e-c7bfec3d6683.png)

**Comment by ryantxu** [comment]
Not that the latest version requires 7.4 to install -- looks like you are running 7.3.


If you need to run on 7.3 it will actually work (just manually unzip the files and stick them in the plugin folder) but the config UI will be a bit funky

**Comment by ryantxu** [comment]
reopen if you are still having problems
