### ISSUE TITLE
Charts blank out during refreshing ... newly introduced with 1.3.1 and Grafana 7.5.2

### ISSUE THREAD

**Issue by ericarnoldy** [grafana/timestream-datasource#84]
Feel free to say won't fix, and know I almost feel guilty for asking ... but a small UI improvement would be if the curves stayed in place until there are new ones.  I think this was introduced in plugin v1.3.1 / Grafana 7.5.2 ...  The curves flash or blank out every time it reloads which gets pretty annoying as a dashboard goes, didn't seem to do this prior to 1.3.1 / 7.5.2 also confirmed in 1.3.1 / 7.5.3 ... InfluxDB / 7.5.3 does not blank out momentarily.

https://user-images.githubusercontent.com/1719486/114060492-a9e48c80-9852-11eb-96c2-0d1a2eb42582.mov

**Comment by farzadpanahi** [comment]
I have the same issue. Any workaround?

**Comment by farzadpanahi** [comment]
@ryantxu have you noticed this issue?

**Comment by andresmgot** [comment]
Closing this in favor of #108
