### ISSUE TITLE
eu-central-1 region missing

### ISSUE THREAD

**Issue by panessa** [grafana/timestream-datasource#87]
Frankfurt regions is supported but eu-central-1 is not in the list.

![image](https://user-images.githubusercontent.com/11522608/119503197-fd5f5b00-bd6a-11eb-853e-f328054e5086.png)

From source code I can clearly see eu-central-1 from src/regions.ts

```javascript
export const standardRegions = ['us-east-1', 'us-east-2', 'us-west-2', 'eu-west-1', 'eu-central-1'];
```

timestream-datasource version v1.3.1
grafana v7.5.7

**Comment by ryantxu** [comment]
This has been included in the latest release 1.3.2:
https://grafana.com/grafana/plugins/grafana-timestream-datasource/?tab=changelog
