### ISSUE TITLE
Connecting Via AWS IAM Assume Role Not Working

### ISSUE THREAD

**Issue by jonmchan** [grafana/timestream-datasource#9]
Trying to utilize AWS Assume Role to access timestream. Confirmed put the .aws folder with the config and credentials file in the proper place in the home directory of the grafana user. Also made sure all permissions is 644. Also confirmed aws default profile works via:

```
$ sudo -u grafana aws timestream-write list-databases
{
    "Databases": [
        {
            "Arn": "xxxxxxxxxxxxxxxxxxxxx",
            "DatabaseName": "xxxxxxxxxxxx",
            "TableCount": 2,
            "KmsKeyId": "xxxxxxxxxxxxxxx",
            "CreationTime": "2020-10-05T11:48:06.024000-05:00",
            "LastUpdatedTime": "2020-10-05T11:48:06.017000-05:00"
        }
    ]
}

```

However, when trying from the grafana UI, I get the following:

> NoCredentialProviders: no valid providers in chain. Deprecated. For verbose messaging see aws.Config.CredentialsChainVerboseErrors

**Comment by ryantxu** [comment]
Can you check with the 1.1.0 release?  the authentication method now matches cloudwatch  https://grafana.com/docs/grafana/latest/datasources/cloudwatch/#authentication

**Comment by jonmchan** [comment]
I can confirm this works now. NOTE: the solution does not honor ~/.aws/config. The config must be manually inputted into the connection details in the plugin settings page.

Assume Role ARN must be set to `role_arn`
Credentials Profile Name must be set to `source_profile`

from the config file.
