### ISSUE TITLE
No "Assume Role ARN" in Timestream datasource config

### ISSUE THREAD

**Issue by kpeters-cbsi** [grafana/timestream-datasource#97]
The [docs](https://grafana.com/grafana/plugins/grafana-timestream-datasource/) say "The Timestream plugin authentication system matches the standard Cloudwatch plugin system.". Looking at the [Cloudwatch documentation](https://grafana.com/docs/grafana/latest/datasources/cloudwatch/#authentication), I see "The `Assume Role ARN` field allows you to specify which IAM role to assume, if any. " There is no "Assume Role ARN" field in the Timestream datasource config (see screenshot). Instead, all I have are "Authentication Provider", "Endpoint", and "Default Region". How do I assume a different Role?

![grafana screenshot](https://user-images.githubusercontent.com/52167998/124794523-bb523900-df14-11eb-9cba-894c0e9a4f24.png)

**Comment by ryantxu** [comment]
What version are you running?  This is what mine looks like:
![image](https://user-images.githubusercontent.com/705951/125692986-406a116e-e8c0-4faf-af50-f859c1ead1c0.png)

**Comment by kpeters-cbsi** [comment]
Grafana v7.4.1 (07649d1313)

![Screenshot 2021-07-21 093113](https://user-images.githubusercontent.com/52167998/126506354-48214cee-bc2f-4a27-949d-1c2ea59e25fd.png)

**Comment by tiratatp** [comment]
@kpeters-cbsi I think he meant Timestream plugin version. The latest is 1.3.3 https://github.com/grafana/timestream-datasource/releases/tag/v1.3.3

**Comment by kpeters-cbsi** [comment]
Oops. :) Timestream plugin 1.3.0. I take it I should upgrade?

**Comment by kpeters-cbsi** [comment]
Updating to 1.3.3 fixed it.
